### PR TITLE
added support to connect to other servers

### PR DESCRIPTION
**Pull request by siueric0010**

### CODE REVIEW

**Comment by siueric0010** [comment]
Note: this requires any accesses to clientChar to be checked in Window.cpp because clientChar is only initialized after we are connected to the server and make decisions on what clientChar should point to. OR, I can first init the clientChar to be the first character and then change it later.

**Comment by siueric0010** [comment]
Preferably, I would wait for #33  to get pushed in before mine because it's easier to fix conflicts on this PR than on that one.

**Comment by siueric0010** [comment]
Includes optimizing animations by only loading the assets during roleClaimed and animation interval changes.

**Review by rajenr — APPROVED** [review]
Thanks so much!

**Pull request merged**
