### PR TITLE
Player objective interaction

### PR DESCRIPTION
**Pull request by siueric0010**
1. Interactions with Objectives possible with key 'E'. Objectives are expected to be far enough to each other so 'E' will only interact with one object. Even if the objects are close together on the grid, one might have to position themselves so they can grab a specific item.
2. Beacon will be captured via players sitting in its interaction area
3. Terminal client updated with interaction ability (also moved test objectives closer to the players)

I will need @darylnak to double check that the code for objectives makes sense and @duouyang because there were many changes to GamePlayer + Job Classes and Game because of this.

### CODE REVIEW

**Comment by siueric0010** [comment]
Sorry for the 30 files changed. A good amount of them are changes to headers or constants (basically half of them).

**Comment by amritakohli** [comment]
Suggest renaming BEAC to BEACON for consistency

**Review by darylnak — COMMENTED** [review]
The files I reviewed look good to me!

**Review by duouyang — APPROVED** [review]
All the code look great! Gonna merge to main. Nice work!

**Pull request merged**
