### PR TITLE
monster uniqueAttack implemented

### PR DESCRIPTION
**Pull request by amritakohli**
used Fighter.cpp attack() to implement Monster uniqueAttack()

### CODE REVIEW

**Review by duouyang — CHANGES_REQUESTED** [review]
Overtime damage is only for Fighter class. Can you remove this feature from the Monster class? Other things all look good to me.

**Comment by siueric0010** [comment]
ping just in case @amritakohli didn't see your comment.

**Comment by amritakohli** [comment]
Updated @duouyang

**Review by duouyang — APPROVED** [review]
Looks good!

**Pull request merged**
